// sanity/schemas/sgProperty.ts
// Murivest — Singapore Institutional Commercial Property Schema
// Single schema covering For Sale, For Rent, Investment Sale, and all institutional asset classes.

import { defineType, defineField, defineArrayMember } from 'sanity';

// ─── Reusable object types (extractable to separate files) ────────────────────
const priceObject = {
  name: 'pricing',
  title: 'Pricing',
  type: 'object',
  fields: [
    { name: 'currency', title: 'Currency', type: 'string', options: { list: ['SGD', 'USD', 'GBP', 'EUR', 'AED', 'KES'] } },
    { name: 'amount', title: 'Amount', type: 'number' },
    { name: 'label', title: 'Display Label', type: 'string', description: 'e.g. "Price on Application", "Guide Price"' },
  ],
  preview: { select: { currency: 'currency', amount: 'amount' }, prepare: ({ currency, amount }: any) => ({ title: `${currency} ${amount?.toLocaleString() ?? ''}` }) },
};

const advisorObject = {
  name: 'advisor',
  title: 'Advisor',
  type: 'object',
  fields: [
    { name: 'name', title: 'Name', type: 'string' },
    { name: 'email', title: 'Email', type: 'string' },
    { name: 'phone', title: 'Phone', type: 'string' },
    { name: 'photo', title: 'Photo', type: 'image', options: { hotspot: true } },
    { name: 'title', title: 'Job Title', type: 'string' },
  ],
};

const tenantObject = {
  name: 'tenant',
  title: 'Tenant',
  type: 'object',
  fields: [
    { name: 'name', title: 'Tenant Name', type: 'string' },
    { name: 'industry', title: 'Industry', type: 'string' },
    { name: 'leasedArea', title: 'Leased Area (sq ft)', type: 'number' },
    { name: 'monthlyRent', title: 'Monthly Rent', type: 'number' },
    { name: 'leaseStart', title: 'Lease Commencement', type: 'date' },
    { name: 'leaseExpiry', title: 'Lease Expiry', type: 'date' },
    { name: 'renewalOptions', title: 'Renewal Options', type: 'string' },
    { name: 'isAnchor', title: 'Anchor Tenant', type: 'boolean', initialValue: false },
  ],
};

export default defineType({
  name: 'sgProperty',
  title: 'Singapore Commercial Property',
  type: 'document',
  groups: [
    { name: 'identity', title: 'Identity & Status' },
    { name: 'classification', title: 'Classification' },
    { name: 'location', title: 'Location' },
    { name: 'planning_land', title: 'Planning & Land' },
    { name: 'pricing', title: 'Pricing' },
    { name: 'specifications', title: 'Asset Specifications' },
    { name: 'building', title: 'Building Intelligence' },
    { name: 'leasing', title: 'Leasing' },
    { name: 'investment', title: 'Investment Metrics' },
    { name: 'tenancy', title: 'Tenancy' },
    { name: 'sustainability', title: 'Sustainability' },
    { name: 'media', title: 'Media & Documents' },
    { name: 'advisory', title: 'Advisory & Transaction' },
    { name: 'compliance', title: 'Compliance' },
    { name: 'seo', title: 'SEO & Discovery' },
  ],

  fields: [
    // ── IDENTITY ─────────────────────────────────────────────────────────────
    defineField({
      name: 'title',
      title: 'Property Title',
      type: 'string',
      group: 'identity',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'identity',
      options: { source: 'title', maxLength: 96 },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle / Tagline',
      type: 'string',
      group: 'identity',
    }),
    defineField({
      name: 'referenceCode',
      title: 'Reference / MLS Code',
      type: 'string',
      group: 'identity',
    }),
    defineField({
      name: 'status',
      title: 'Availability Status',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          'Available',
          'Under Offer',
          'Reserved',
          'Sold / Leased',
          'Coming Soon',
        ],
      },
      initialValue: 'Available',
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured Listing',
      type: 'boolean',
      group: 'identity',
      initialValue: false,
    }),
    defineField({
      name: 'isExclusive',
      title: 'Exclusive Mandate',
      type: 'boolean',
      group: 'identity',
      initialValue: false,
    }),
    defineField({
      name: 'isOffMarket',
      title: 'Off-Market / Confidential',
      type: 'boolean',
      group: 'identity',
      initialValue: false,
    }),

    // ── CLASSIFICATION ───────────────────────────────────────────────────────
    defineField({
      name: 'assetClass',
      title: 'Asset Class',
      type: 'string',
      group: 'classification',
      options: {
        list: [
          'Office',
          'Retail',
          'Industrial',
          'Logistics',
          'Warehouse',
          'Data Centre',
          'Business Park',
          'Science Park',
          'Healthcare',
          'Medical',
          'Hotel',
          'Serviced Apartment',
          'Student Housing',
          'PBSA',
          'Mixed Use',
          'Land',
          'Commercial Strata',
          'Shophouse',
          'Life Sciences',
          'Self Storage',
          'Infrastructure',
          'Build-to-Suit',
          'Development Site',
        ],
      },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'listingType',
      title: 'Listing Type',
      type: 'string',
      group: 'classification',
      options: {
        list: [
          'For Sale',
          'For Rent',
          'Investment Sale',
          'Sale & Leaseback',
          'Build-to-Suit',
          'Sublease',
          'Assignment',
          'Off Market',
          'Confidential Listing',
          'Owner Occupier',
          'Joint Venture Opportunity',
        ],
      },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'propertyType',
      title: 'Property Subtype',
      type: 'string',
      group: 'classification',
      description: 'e.g. Grade A Office, Strip Retail, Cold Storage, etc.',
    }),
    defineField({
      name: 'buildingGrade',
      title: 'Building Grade',
      type: 'string',
      group: 'classification',
      options: { list: ['Grade A', 'Grade B', 'Grade C', 'Core', 'Core+', 'Value Add', 'Opportunistic'] },
    }),

    // ── LOCATION ─────────────────────────────────────────────────────────────
    defineField({
      name: 'country',
      title: 'Country',
      type: 'string',
      group: 'location',
      initialValue: 'Singapore',
      readOnly: true,
      hidden: true,
    }),
    defineField({
      name: 'address',
      title: 'Full Address',
      type: 'string',
      group: 'location',
    }),
    defineField({
      name: 'postalCode',
      title: 'Postal Code',
      type: 'string',
      group: 'location',
    }),
    defineField({
      name: 'planningRegion',
      title: 'Planning Region',
      type: 'string',
      group: 'location',
      options: { list: ['Central', 'East', 'North', 'North-East', 'West'] },
    }),
    defineField({
      name: 'district',
      title: 'District / CBD Submarket',
      type: 'string',
      group: 'location',
      description: 'e.g. Raffles Place, Marina Bay, Orchard, Jurong East',
    }),
    defineField({
      name: 'coordinates',
      title: 'GPS Coordinates',
      type: 'object',
      group: 'location',
      fields: [
        { name: 'lat', title: 'Latitude', type: 'number' },
        { name: 'lng', title: 'Longitude', type: 'number' },
      ],
    }),

    // ── PLANNING & LAND (Singapore‑specific) ────────────────────────────────
    defineField({
      name: 'uraZoning',
      title: 'URA Zoning',
      type: 'string',
      group: 'planning_land',
      description: 'e.g. Commercial, Residential, Hotel, White, Business Park, B1, B2',
    }),
    defineField({
      name: 'grossPlotRatio',
      title: 'Gross Plot Ratio (GPR)',
      type: 'number',
      group: 'planning_land',
    }),
    defineField({
      name: 'plotRatio',
      title: 'Plot Ratio',
      type: 'number',
      group: 'planning_land',
    }),
    defineField({
      name: 'siteArea',
      title: 'Site Area (sq ft)',
      type: 'number',
      group: 'planning_land',
    }),
    defineField({
      name: 'landTenure',
      title: 'Land Tenure',
      type: 'string',
      group: 'planning_land',
      options: { list: ['Freehold', '999-year', '99-year', '60-year', 'JTC Lease', 'Other'] },
    }),
    defineField({
      name: 'jtcLeaseDetails',
      title: 'JTC Lease Details',
      type: 'text',
      group: 'planning_land',
      rows: 2,
    }),
    defineField({
      name: 'topDate',
      title: 'TOP (Temporary Occupation Permit) Date',
      type: 'date',
      group: 'planning_land',
    }),
    defineField({
      name: 'greenMarkCertification',
      title: 'Green Mark Certification',
      type: 'string',
      group: 'planning_land',
      options: { list: ['Platinum', 'GoldPLUS', 'Gold', 'Certified', 'None'] },
    }),
    defineField({
      name: 'businessParkClassification',
      title: 'Business Park Classification',
      type: 'string',
      group: 'planning_land',
      description: 'e.g. Science Park, High-Tech, General',
    }),
    defineField({
      name: 'industrialType',
      title: 'Industrial Type (B1/B2)',
      type: 'string',
      group: 'planning_land',
      options: { list: ['B1', 'B2', 'B1/B2'] },
    }),

    // ── PRICING (multi‑currency, flexible) ────────────────────────────────────
    defineField({
      name: 'prices',
      title: 'Prices',
      type: 'array',
      group: 'pricing',
      of: [priceObject],
      description: 'Add prices in relevant currencies. Use "Price on Application" labels if required.',
    }),

    // ── ASSET SPECIFICATIONS ─────────────────────────────────────────────────
    defineField({
      name: 'grossFloorArea',
      title: 'Gross Floor Area (sq ft)',
      type: 'number',
      group: 'specifications',
    }),
    defineField({
      name: 'netLettableArea',
      title: 'Net Lettable Area (sq ft)',
      type: 'number',
      group: 'specifications',
    }),
    defineField({
      name: 'floorPlate',
      title: 'Typical Floor Plate (sq ft)',
      type: 'number',
      group: 'specifications',
    }),
    defineField({
      name: 'ceilingHeight',
      title: 'Ceiling Height (m)',
      type: 'number',
      group: 'specifications',
    }),
    defineField({
      name: 'powerCapacity',
      title: 'Power Capacity',
      type: 'string',
      group: 'specifications',
      description: 'e.g. 100 amps per floor, 10 kVA',
    }),
    defineField({
      name: 'raisedFloors',
      title: 'Raised Floors',
      type: 'boolean',
      group: 'specifications',
    }),
    defineField({
      name: 'airConditioning',
      title: 'Air Conditioning',
      type: 'string',
      group: 'specifications',
      options: { list: ['Central', 'Split', 'VRF', 'None'] },
    }),

    // ── BUILDING INTELLIGENCE ─────────────────────────────────────────────────
    defineField({
      name: 'buildingName',
      title: 'Building Name',
      type: 'string',
      group: 'building',
    }),
    defineField({
      name: 'developer',
      title: 'Developer',
      type: 'string',
      group: 'building',
    }),
    defineField({
      name: 'architect',
      title: 'Architect',
      type: 'string',
      group: 'building',
    }),
    defineField({
      name: 'propertyManager',
      title: 'Property Manager',
      type: 'string',
      group: 'building',
    }),
    defineField({
      name: 'yearBuilt',
      title: 'Year Built',
      type: 'number',
      group: 'building',
    }),
    defineField({
      name: 'majorRefurbishment',
      title: 'Major Refurbishment Year',
      type: 'number',
      group: 'building',
    }),
    defineField({
      name: 'floorCount',
      title: 'Number of Floors',
      type: 'number',
      group: 'building',
    }),
    defineField({
      name: 'passengerLifts',
      title: 'Passenger Lifts',
      type: 'number',
      group: 'building',
    }),
    defineField({
      name: 'cargoLifts',
      title: 'Cargo Lifts',
      type: 'number',
      group: 'building',
    }),
    defineField({
      name: 'loadingBays',
      title: 'Loading Bays',
      type: 'number',
      group: 'building',
    }),
    defineField({
      name: 'parkingSpaces',
      title: 'Parking Spaces',
      type: 'number',
      group: 'building',
    }),
    defineField({
      name: 'amenities',
      title: 'Amenities',
      type: 'array',
      group: 'building',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'security',
      title: 'Security Features',
      type: 'array',
      group: 'building',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'e.g. 24/7 security, CCTV, card access',
    }),
    defineField({
      name: 'smartBuildingFeatures',
      title: 'Smart Building Features',
      type: 'array',
      group: 'building',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'telecomProviders',
      title: 'Telecommunication Providers',
      type: 'array',
      group: 'building',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'buildingCertifications',
      title: 'Building Certifications',
      type: 'array',
      group: 'building',
      of: [{ type: 'string' }],
      description: 'e.g. Green Mark, LEED Platinum, WELL Gold',
    }),

    // ── LEASING ──────────────────────────────────────────────────────────────
    defineField({
      name: 'monthlyRent',
      title: 'Monthly Rent',
      type: 'number',
      group: 'leasing',
      description: 'Base monthly rent in SGD',
    }),
    defineField({
      name: 'annualRent',
      title: 'Annual Rent',
      type: 'number',
      group: 'leasing',
    }),
    defineField({
      name: 'rentPsf',
      title: 'Rent per sq ft (per month)',
      type: 'number',
      group: 'leasing',
    }),
    defineField({
      name: 'serviceCharge',
      title: 'Service Charge (per sq ft/month)',
      type: 'number',
      group: 'leasing',
    }),
    defineField({
      name: 'availability',
      title: 'Availability',
      type: 'string',
      group: 'leasing',
      description: 'e.g. Immediate, Q3 2027',
    }),
    defineField({
      name: 'leaseType',
      title: 'Lease Type',
      type: 'string',
      group: 'leasing',
      options: { list: ['New Lease', 'Renewal', 'Sublease', 'Assignment', 'Flexible'] },
    }),
    defineField({
      name: 'leaseCommencement',
      title: 'Lease Commencement Date',
      type: 'date',
      group: 'leasing',
    }),
    defineField({
      name: 'leaseExpiry',
      title: 'Lease Expiry Date',
      type: 'date',
      group: 'leasing',
    }),
    defineField({
      name: 'fitOutCondition',
      title: 'Fit Out Condition',
      type: 'string',
      group: 'leasing',
      options: { list: ['Bare Shell', 'Warm Shell', 'Fitted', 'Plug & Play'] },
    }),
    defineField({
      name: 'rentFreePeriod',
      title: 'Rent‑Free Period (months)',
      type: 'number',
      group: 'leasing',
    }),
    defineField({
      name: 'minimumLease',
      title: 'Minimum Lease Term (years)',
      type: 'number',
      group: 'leasing',
    }),
    defineField({
      name: 'maximumLease',
      title: 'Maximum Lease Term (years)',
      type: 'number',
      group: 'leasing',
    }),
    defineField({
      name: 'escalation',
      title: 'Escalation Rate (% per annum)',
      type: 'number',
      group: 'leasing',
    }),
    defineField({
      name: 'operatingExpenses',
      title: 'Operating Expenses',
      type: 'text',
      group: 'leasing',
    }),
    defineField({
      name: 'furniture',
      title: 'Furnished',
      type: 'boolean',
      group: 'leasing',
    }),
    defineField({
      name: 'managedOffice',
      title: 'Managed Office',
      type: 'boolean',
      group: 'leasing',
    }),
    defineField({
      name: 'coWorking',
      title: 'Co‑Working Space',
      type: 'boolean',
      group: 'leasing',
    }),
    defineField({
      name: 'flexibleLease',
      title: 'Flexible Lease Options',
      type: 'boolean',
      group: 'leasing',
    }),

    // ── INVESTMENT METRICS ────────────────────────────────────────────────────
    defineField({
      name: 'askingPrice',
      title: 'Asking Price (SGD)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'pricePsf',
      title: 'Price per sq ft (SGD)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'capitalValue',
      title: 'Capital Value (SGD)',
      type: 'number',
      group: 'investment',
      description: 'Appraised value',
    }),
    defineField({
      name: 'noi',
      title: 'Net Operating Income (SGD)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'capRate',
      title: 'Cap Rate (%)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'irr',
      title: 'IRR (%)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'yield',
      title: 'Gross Yield (%)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'wale',
      title: 'WALE (years)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'occupancyRate',
      title: 'Occupancy Rate (%)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'tenantProfile',
      title: 'Tenant Profile Summary',
      type: 'text',
      group: 'investment',
    }),
    defineField({
      name: 'anchorTenant',
      title: 'Anchor Tenant',
      type: 'string',
      group: 'investment',
    }),
    defineField({
      name: 'rentalGrowth',
      title: 'Rental Growth (% pa)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'projectedAppreciation',
      title: 'Projected Capital Appreciation (% pa)',
      type: 'number',
      group: 'investment',
    }),
    defineField({
      name: 'developmentPotential',
      title: 'Development / Redevelopment Potential',
      type: 'text',
      group: 'investment',
    }),
    defineField({
      name: 'valueAddOpportunity',
      title: 'Value‑Add Opportunity',
      type: 'text',
      group: 'investment',
    }),
    defineField({
      name: 'investmentHighlights',
      title: 'Investment Highlights',
      type: 'array',
      group: 'investment',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'riskProfile',
      title: 'Risk Profile',
      type: 'string',
      group: 'investment',
      options: { list: ['Low', 'Moderate', 'High', 'Speculative'] },
    }),
    defineField({
      name: 'exitStrategy',
      title: 'Exit Strategy',
      type: 'text',
      group: 'investment',
    }),
    defineField({
      name: 'institutionalGrade',
      title: 'Institutional Grade',
      type: 'boolean',
      group: 'investment',
      description: 'Meets institutional investment criteria',
    }),
    defineField({
      name: 'investmentCommitteeNotes',
      title: 'Investment Committee Notes',
      type: 'text',
      group: 'investment',
    }),

    // ── TENANCY (multiple tenants) ───────────────────────────────────────────
    defineField({
      name: 'tenants',
      title: 'Tenant Roster',
      type: 'array',
      group: 'tenancy',
      of: [tenantObject],
    }),

    // ── SUSTAINABILITY ───────────────────────────────────────────────────────
    defineField({
      name: 'greenMarkLevel',
      title: 'Green Mark Level',
      type: 'string',
      group: 'sustainability',
      options: { list: ['Platinum', 'GoldPLUS', 'Gold', 'Certified', 'None'] },
    }),
    defineField({
      name: 'leedCertification',
      title: 'LEED Certification',
      type: 'string',
      group: 'sustainability',
      options: { list: ['Platinum', 'Gold', 'Silver', 'Certified'] },
    }),
    defineField({
      name: 'wellCertification',
      title: 'WELL Certification',
      type: 'string',
      group: 'sustainability',
      options: { list: ['Platinum', 'Gold', 'Silver', 'Certified'] },
    }),
    defineField({
      name: 'energyRating',
      title: 'Energy Rating',
      type: 'string',
      group: 'sustainability',
    }),
    defineField({
      name: 'solarPanels',
      title: 'Solar Panels',
      type: 'boolean',
      group: 'sustainability',
    }),
    defineField({
      name: 'waterEfficiency',
      title: 'Water Efficiency',
      type: 'text',
      group: 'sustainability',
    }),
    defineField({
      name: 'carbonFootprint',
      title: 'Carbon Footprint (kgCO2/m²/yr)',
      type: 'number',
      group: 'sustainability',
    }),
    defineField({
      name: 'evCharging',
      title: 'EV Charging Stations',
      type: 'number',
      group: 'sustainability',
    }),
    defineField({
      name: 'esgRating',
      title: 'ESG Rating',
      type: 'string',
      group: 'sustainability',
    }),
    defineField({
      name: 'climateRisk',
      title: 'Climate Risk Assessment',
      type: 'text',
      group: 'sustainability',
    }),

    // ── MEDIA & DOCUMENTS ────────────────────────────────────────────────────
    defineField({
      name: 'heroImage',
      title: 'Hero / Cover Image',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
    }),
    defineField({
      name: 'gallery',
      title: 'Image Gallery',
      type: 'array',
      group: 'media',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'floorPlans',
      title: 'Floor Plans',
      type: 'array',
      group: 'media',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'sitePlan',
      title: 'Site Plan',
      type: 'image',
      group: 'media',
    }),
    defineField({
      name: 'masterPlan',
      title: 'Master Plan',
      type: 'image',
      group: 'media',
    }),
    defineField({
      name: 'locationMap',
      title: 'Location Map',
      type: 'image',
      group: 'media',
    }),
    defineField({
      name: 'droneImages',
      title: 'Drone Images',
      type: 'array',
      group: 'media',
      of: [{ type: 'image' }],
    }),
    defineField({
      name: 'videos',
      title: 'Videos',
      type: 'array',
      group: 'media',
      of: [{ type: 'url' }],
    }),
    defineField({
      name: 'virtualTour',
      title: 'Virtual Tour URL',
      type: 'url',
      group: 'media',
    }),
    defineField({
      name: 'investmentMemorandum',
      title: 'Investment Memorandum (PDF)',
      type: 'file',
      group: 'media',
    }),
    defineField({
      name: 'brochure',
      title: 'Brochure (PDF)',
      type: 'file',
      group: 'media',
    }),
    defineField({
      name: 'financialModel',
      title: 'Financial Model (Excel)',
      type: 'file',
      group: 'media',
    }),
    defineField({
      name: 'dataRoom',
      title: 'Data Room Documents',
      type: 'array',
      group: 'media',
      of: [{ type: 'file' }],
    }),

    // ── ADVISORY & TRANSACTION ────────────────────────────────────────────────
    defineField({
      name: 'leadAdvisor',
      title: 'Lead Advisor',
      type: 'object',
      group: 'advisory',
      fields: advisorObject.fields,
    }),
    defineField({
      name: 'coBroker',
      title: 'Co‑Broker / Joint Agent',
      type: 'object',
      group: 'advisory',
      fields: advisorObject.fields,
    }),
    defineField({
      name: 'valuer',
      title: 'Valuer',
      type: 'string',
      group: 'advisory',
    }),
    defineField({
      name: 'lawFirm',
      title: 'Law Firm',
      type: 'string',
      group: 'advisory',
    }),
    defineField({
      name: 'dueDiligenceStatus',
      title: 'Due Diligence Status',
      type: 'string',
      group: 'advisory',
      options: { list: ['Not Started', 'In Progress', 'Completed'] },
    }),
    defineField({
      name: 'ndaRequired',
      title: 'NDA Required',
      type: 'boolean',
      group: 'advisory',
      initialValue: false,
    }),
    defineField({
      name: 'confidentialListing',
      title: 'Confidential Listing',
      type: 'boolean',
      group: 'advisory',
      initialValue: false,
    }),
    defineField({
      name: 'vendorType',
      title: 'Vendor Type',
      type: 'string',
      group: 'advisory',
    }),
    defineField({
      name: 'purchaserType',
      title: 'Target Purchaser / Tenant Profile',
      type: 'string',
      group: 'advisory',
    }),
    defineField({
      name: 'targetInvestor',
      title: 'Target Investor',
      type: 'string',
      group: 'advisory',
    }),
    defineField({
      name: 'foreignOwnershipRestrictions',
      title: 'Foreign Ownership Restrictions',
      type: 'text',
      group: 'advisory',
    }),
    defineField({
      name: 'transactionStage',
      title: 'Transaction Stage',
      type: 'string',
      group: 'advisory',
      options: { list: ['Off Market', 'Marketing', 'Under Offer', 'Exchanged', 'Completed'] },
    }),
    defineField({
      name: 'dealStatus',
      title: 'Deal Status',
      type: 'string',
      group: 'advisory',
      options: { list: ['Open', 'Under Contract', 'Closed', 'Withdrawn'] },
    }),
    defineField({
      name: 'complianceNotes',
      title: 'Compliance Notes',
      type: 'text',
      group: 'advisory',
    }),

    // ── COMPLIANCE ────────────────────────────────────────────────────────────
    defineField({
      name: 'regulatoryNote',
      title: 'Regulatory / Legal Notes',
      type: 'text',
      group: 'compliance',
      rows: 3,
    }),

    // ── SEO & DISCOVERY ───────────────────────────────────────────────────────
    defineField({
      name: 'metaTitle',
      title: 'Meta Title',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'text',
      group: 'seo',
      rows: 2,
    }),
    defineField({
      name: 'keywords',
      title: 'Keywords',
      type: 'array',
      group: 'seo',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical URL',
      type: 'url',
      group: 'seo',
    }),
    defineField({
      name: 'publishedAt',
      title: 'First Published',
      type: 'datetime',
      group: 'seo',
    }),
  ],

});