import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { Hero, MarketCards, PublicPage, TrustStrip } from './PublicSite'

const homepageServices = ['Acquisition advisory', 'Disposition strategy', 'Capital introductions', 'Commercial property research']

export default function HomePage() {
  return <PublicPage>
    <Hero eyebrow="Independent commercial real estate advisory" title="Local intelligence. Institutional discipline." description="Murivest is a Nairobi-founded advisory practice helping owners, investors, and occupiers navigate commercial property mandates across selected gateway markets." />
    <TrustStrip />
    <section className="border-b border-[var(--mv-line)] bg-[var(--mv-paper)]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 lg:grid-cols-[1fr_1.4fr] lg:px-8"><div><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[var(--mv-brass)]">Find a starting point</p><h2 className="mt-4 font-serif text-3xl text-[var(--mv-forest)]">What brings you here?</h2></div><div className="grid gap-3 sm:grid-cols-3"><Link href="/contact?type=acquisition" className="border border-[var(--mv-line)] bg-[var(--mv-cream)] p-5 text-sm font-semibold text-[var(--mv-forest)] hover:border-[var(--mv-brass)]">Acquire an asset <ArrowUpRight size={15} className="mt-5 text-[var(--mv-brass)]" /></Link><Link href="/contact?type=disposition" className="border border-[var(--mv-line)] bg-[var(--mv-cream)] p-5 text-sm font-semibold text-[var(--mv-forest)] hover:border-[var(--mv-brass)]">Explore a disposition <ArrowUpRight size={15} className="mt-5 text-[var(--mv-brass)]" /></Link><Link href="/research" className="border border-[var(--mv-line)] bg-[var(--mv-cream)] p-5 text-sm font-semibold text-[var(--mv-forest)] hover:border-[var(--mv-brass)]">Read research <ArrowUpRight size={15} className="mt-5 text-[var(--mv-brass)]" /></Link></div></div></section>
    <MarketCards />
    <section className="bg-[var(--mv-paper)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[var(--mv-brass)]">A measured model</p><h2 className="mt-4 max-w-lg font-serif text-4xl leading-tight text-[var(--mv-forest)]">We do not manufacture certainty. We make the next decision clearer.</h2></div><div><p className="text-base leading-8 text-[var(--mv-muted)]">Our work starts with a defined mandate, a clear counterparty, and a shared understanding of risk. We connect local market context with a disciplined process for commercial property decisions.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{homepageServices.map((service) => <div key={service} className="border-t border-[var(--mv-line)] pt-4 text-sm font-semibold text-[var(--mv-forest)]">{service}</div>)}</div><Link href="/about" className="mt-10 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[var(--mv-forest)]">How we work <ArrowUpRight size={15} /></Link></div></div></section>
  </PublicPage>
}
