import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { Disclosure, Hero, MarketCards, PublicPage, TrustStrip, markets } from './PublicSite'

type Market = typeof markets[number]

export default function MarketPage({ market, sectors, intro }: { market: Market; sectors: string[]; intro: string }) {
  return <PublicPage><Hero eyebrow={`${market.region} · ${market.name}`} title={`Commercial property intelligence for ${market.name}.`} description={intro} cta="Discuss a mandate" /><TrustStrip /><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-14 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[var(--mv-brass)]">Focus areas</p><h2 className="mt-4 font-serif text-4xl text-[var(--mv-forest)]">A considered market entry.</h2></div><div><p className="text-base leading-8 text-[var(--mv-muted)]">We work with verified counterparties and defined mandates. Current availability is shared privately after an initial enquiry and appropriate KYC.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{sectors.map((sector) => <div key={sector} className="border-t border-[var(--mv-line)] pt-4 text-sm font-semibold text-[var(--mv-forest)]">{sector}</div>)}</div><Disclosure /></div></div></section><section className="bg-[var(--mv-paper)]"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[var(--mv-brass)]">Verified inventory</p><h2 className="mt-4 font-serif text-4xl text-[var(--mv-forest)]">Mandate window open</h2></div><Link href="/contact" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[var(--mv-forest)]">Request availability <ArrowUpRight size={15} /></Link></div><div className="mt-8 border border-dashed border-[var(--mv-brass)]/60 p-8 text-sm leading-7 text-[var(--mv-muted)]">No public listings are displayed until asset, ownership, availability, and counterparty details are verified for release. Share your criteria and our team will respond with the appropriate market window.</div></div></section><MarketCards /></PublicPage>
}
