'use client';

import { Search, Filter, TrendingUp, ArrowRight, Clock, Mail, User, Calendar } from 'lucide-react';
import React, { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { motion } from 'framer-motion';

interface Blog {
  id: string;
  title: string;
  excerpt: string;
  author: string;
  category: string;
  date: string;
  readTime: string;
  image: string;
  featured?: boolean;
  content?: string;
}

const blog: Blog[] =[
  {
    id: 'nairobi-cbd-office-market-analysis-2026',
    title: 'Nairobi CBD Office Market Analysis 2026: Trends, Yields & Opportunities',
    excerpt:
      'An in-depth analysis of Nairobi CBD\'s office market in 2026, covering vacancy rates, rental trends, key developments, and investment opportunities.',
    author: 'Murivest Research Team',
    category: 'Market Analysis',
    date: '2024-08-10',
    readTime: '30 min read',
    image:'https://properties.avenuevaluers.co.ke/wp-content/uploads/2026/01/Grade-A-offices-in-nairobi.jpg',
    featured: true,
  },
  {
    id: 'improve-credit-score-property-loans-kenya',
    title: 'How to Improve Your Credit Score for Property Loans in Kenya',
    excerpt: 'A vital guide for aspiring homeowners in Kenya, detailing actionable steps to enhance your credit score and secure favorable property loan terms in 2025.',
    author: 'Esther Wanjiku',
    category: 'Financing',
    date: '2025-06-15',
    readTime: '8 min read',
    image: 'https://www.pesapal.com/media/118211/02_25-pesapal-ea-blog-how-to-improve-your-credit-score-1.png?center=0.49805447470817121,0.49833333333333335&mode=crop&width=355&height=218&rnd=133863137910000000',
    featured: false,
  },
  {
    id: 'special-warranty-deed',
    title: 'Special Warranty Deed: Understanding Real Estate Transactions',
    excerpt: 'Understand how a special warranty deed works, what risks it shifts to the buyer, and how to protect your investment in commercial real estate deals.',
    author: 'LoopNet Team',
    category: 'Investing',
    date: 'September 28, 2025',
    readTime: '7 min read',
    image: 'https://images.pexels.com/photos/4386431/pexels-photo-4386431.jpeg?auto=compress&cs=tinysrgb&w=1200',
    featured: false,
  },
  {
    id: 'what-is-a-cap-rate',
    title: 'What Is a Cap Rate? Calculating This Critical CRE Investment Metric',
    excerpt: 'A capitalization (cap) rate is a measurement of the perceived risk of owning a property, expressing an anticipated annual return on an investment. Learn how to calculate cap rates and why this metric matters.',
    author: 'LoopNet Team',
    category: 'Investing',
    date: 'September 18, 2025',
    readTime: '10 min read',
    image: 'https://www.loopnet.com/s/images/what-is-a-cap-rate/cap-rate-range-chart.webp',
    featured: true,
  },
  {
    id: "ngong-heritage-villas",
    title: "NGONG: The New Luxury Frontier for Kenya's Elite Families",
    excerpt: "The market has spoken: While traditional luxury enclaves like Kilimani face oversupply, Ngong is emerging as Kenya's premier lifestyle destination with property values appreciating faster than ever.",
    author: "Ngong Heritage Villas",
    category: "Luxury Properties",
    date: "2025-07-01",
    readTime: "3 min read",
    image: "/p17 heritage/IMG-20250421-WA0093.jpg",
    featured: false
  },
  {
    id: 'unlocking-homeownership-mortgages-kenya',
    title: 'Unlocking Homeownership: A Comprehensive Guide to Mortgages in Kenya',
    excerpt: 'Demystify the mortgage application process in Kenya for 2025, exploring different types of mortgages, eligibility criteria, and tips for first-time homebuyers.',
    author: 'David Mwangi',
    category: 'Homeownership',
    date: '2025-06-20',
    readTime: '12 min read',
    image: 'https://www.buyrentkenya.com/discover/wp-content/uploads/2024/05/brkmarketing-image-of-a-home-owner-in-nairobi-opening-the-door-4b1ed9cc-114b-43d6-b025-479561f02c7b.png',
    featured: true,
  },
  {
    id: 'step-by-step-home-insurance-kenya',
    title: 'Step-by-Step Guide on Home Insurance in Kenya: Protecting Your Investment',
    excerpt: 'Understand the essentials of home insurance in Kenya, including coverage types, benefits, and how to choose the right policy to safeguard your property in 2025.',
    author: 'Grace Adhiambo',
    category: 'Property Management',
    date: '2025-06-25',
    readTime: '9 min read',
    image: 'https://stepbystepinsurance.co.ke/wp-content/uploads/2024/09/Home-Insurance.png',
    featured: false,
  },
  {
    id: 'affordable-housing-kenya-2025',
    title: 'Affordable Housing in Kenya 2025: Opportunities and Challenges',
    excerpt: 'An in-depth look at the progress and hurdles in Kenya\'s affordable housing sector for 2025, highlighting government initiatives and private sector contributions.',
    author: 'Samwel Kimani',
    category: 'Development',
    date: '2025-07-01',
    readTime: '11 min read',
    image: 'https://cdn.radioafrica.digital/image/2025/04/6b35a210-6d7e-4e99-bf51-95c1f4b34e8f.jpeg',
    featured: true,
  },
  {
    id: 'housing-levy-bill-passes-kenya-kwanza',
    title: 'The Housing Levy Bill Passes: A Major Win for Kenya Kwanza\'s Affordable Housing Agenda',
    excerpt: 'Analyzing the implications of the recently passed Housing Levy Bill for affordable housing development and its impact on Kenyans in 2025.',
    author: 'Christine Wanjiru',
    category: 'Policy',
    date: '2025-07-05',
    readTime: '10 min read',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEYfxCyZ5PcwMk5J0frim4jkzopToSwUkffw&s',
    featured: false,
  },
  {
    id: 'kmrc-mortgage-limit-increase-2025',
    title: 'KMRC to Increase Mortgage Limit to KES 10.5M: What it Means for Kenyan Homebuyers',
    excerpt: 'Exploring the significant impact of KMRC\'s increased mortgage limit on accessibility to homeownership for a broader segment of Kenyans in 2025.',
    author: 'Daniel Omondi',
    category: 'Financing',
    date: '2025-07-10',
    readTime: '9 min read',
    image: 'https://sarabirealtygroup.co.ke/wp-content/uploads/2024/06/127757575_202039111572524_5932344972577205189_n.jpg',
    featured: false,
  },
  {
    id: 'sacco-loans-homeownership-kenya',
    title: 'Sacco Loans: Fueling 33% of New Homeownership in Kenya',
    excerpt: 'Discover how SACCOs are becoming a powerful force in enabling homeownership in Kenya, providing flexible and accessible financing options for many in 2025.',
    author: 'Sarah Njeri',
    category: 'Financing',
    date: '2025-07-15',
    readTime: '8 min read',
    image: 'https://www.buyrentkenya.com/discover/wp-content/uploads/2023/09/brkmarketing-people-getting-a-loan-in-a-bank-setup-in-nairobi-k-885d9937-59d8-4b47-aee5-bf3f4432be06-1.png',
    featured: false,
  },
  {
    id: 'unity-homes-absa-bank-affordable-housing',
    title: 'Unity Homes and Absa Bank Partnership: Paving the Way for Affordable Housing in Kenya',
    excerpt: 'A detailed look into the strategic partnership between Unity Homes and Absa Bank and its expected contribution to boosting affordable housing supply in Kenya for 2025.',
    author: 'Paul Kamau',
    category: 'Partnerships',
    date: '2025-07-20',
    readTime: '10 min read',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1uiJUtz_NBf4XX2wvbC6Ru-YrdtV8o8nRtA&s',
    featured: false,
  },
  {
    id: 'dual-impact-housing-levy-kenya',
    title: 'The Dual Impact of the Housing Levy in Kenya: A Deep Dive for Property Owners and Buyers',
    excerpt: 'Examining the multifaceted effects of Kenya\'s Housing Levy on both property owners and prospective buyers, analyzing its benefits and potential challenges in 2025.',
    author: 'Joyce Achieng',
    category: 'Policy',
    date: '2025-07-25',
    readTime: '11 min read',
    image: 'https://kenyahomes.co.ke/blog/wp-content/uploads/2019/04/Affordable-housing-in-Kenya-and-growth-in-real-estate-industry-1024x684.jpg',
    featured: false,
  },
  {
    id: 'service-charge-kenya-what-to-know',
    title: 'Service Charge in Kenya: What Property Owners and Tenants Need to Know in 2025',
    excerpt: 'A comprehensive guide to understanding service charges in Kenyan real estate, clarifying rights, responsibilities, and common disputes for 2025.',
    author: 'Kevin Mwangi',
    category: 'Legal',
    date: '2025-08-01',
    readTime: '9 min read',
    image: 'https://housingfinanceafrica.org/wp-content/uploads/2025/01/teabrice.png',
    featured: false,
  },
  {
    id: 'emerging-real-estate-trends-kenya-2025',
    title: 'Emerging Real Estate Trends in Kenya 2025: Shaping the Market Landscape',
    excerpt: 'Stay ahead of the curve with insights into the latest real estate trends in Kenya for 2025, including technological advancements, sustainable development, and investor preferences.',
    author: 'Cynthia Akinyi',
    category: 'Market Trends',
    date: '2025-08-05',
    readTime: '12 min read',
    image: 'https://epicprime.co.ke/wp-content/uploads/2025/01/5.png',
    featured: true,
  },
  {
    id: 'current-state-real-estate-kenya-2025-outlook',
    title: 'The Current State of the Real Estate Market in Kenya: A 2025 Outlook',
    excerpt: 'An expert analysis of the current health and future projections of Kenya\'s real estate market in 2025, covering investment opportunities and challenges.',
    author: 'Robert Kiptoo',
    category: 'Market Analysis',
    date: '2025-08-10',
    readTime: '10 min read',
    image: 'https://www.policeinvestment.com/wp-content/uploads/2025/04/Kenyas-Real-Estate-Market-Trends.png',
    featured: false,
  },
  {
    id: 'impact-sgr-real-estate-kenya-decade-on',
    title: 'Impact of the Standard Gauge Railway (SGR) on Kenya\'s Real Estate Industry: A Decade On',
    excerpt: 'A retrospective and prospective analysis of how the SGR has transformed real estate development and property values along its corridor in Kenya over the past decade.',
    author: 'Elizabeth Wairimu',
    category: 'Infrastructure',
    date: '2025-08-15',
    readTime: '11 min read',
    image: 'https://chinaglobalsouth.com/wp-content/uploads/2025/03/Kenya-SGR-Site-768x432.jpg',
    featured: false,
  },
  {
    id: 'real-estate-events-kenya-october-2025',
    title: 'Real Estate Events in Kenya: Your October 2025 Networking and Investment Guide',
    excerpt: 'A curated list of top real estate events, expos, and conferences happening in Kenya in October 2025, essential for networking and investment opportunities.',
    author: 'Brian Kipkemboi',
    category: 'Events',
    date: '2025-08-20',
    readTime: '7 min read',
    image: 'https://property254.co.ke/blogUploadedImages/1026/conversions/418-main.jpg',
    featured: false,
  },
  {
    id: 'most-expensive-cities-africa-2025-nairobi',
    title: 'Most Expensive Cities to Live in Africa 2025: Where Does Nairobi Stand?',
    excerpt: 'Comparing Nairobi\'s cost of living and real estate prices against other major African cities in 2025, offering insights for residents and investors.',
    author: 'Angela Moraa',
    category: 'Lifestyle',
    date: '2025-08-25',
    readTime: '9 min read',
    image: 'https://cdn.businessday.ng/wp-content/uploads/2025/01/Top-5-cities-in-Africa-with-highest-cost-of-living-in-2025.png',
    featured: false,
  },
  {
    id: 'housing-menace-nairobi-high-rise-development',
    title: 'The Housing Menace in Nairobi: Navigating High-Rise Development and Urban Sprawl',
    excerpt: 'An examination of Nairobi\'s rapid vertical and horizontal expansion, its implications for urban planning, infrastructure, and housing affordability in 2025.',
    author: 'James Kariuki',
    category: 'Urban Development',
    date: '2025-09-01',
    readTime: '12 min read',
    image: 'https://i.ytimg.com/vi/PaKHjJstPBc/mqdefault.jpg',
    featured: true,
  },
  {
    id: 'navigating-kenya-real-estate-ms-expert',
    title: 'Navigating Kenya\'s Real Estate Landscape with Ms. [Expert Name]: Key Insights for 2025',
    excerpt: 'An exclusive interview with a leading real estate expert, Ms. [Expert Name], providing invaluable insights and predictions for the Kenyan property market in 2025.',
    author: 'Editor',
    category: 'Expert Interview',
    date: '2025-09-05',
    readTime: '10 min read',
    image: 'https://property254.co.ke/blogs/wp-content/uploads/2024/05/Navigating-Kenyas-real-estate-market.jpg',
    featured: false,
  },
  {
    id: 'land-buying-selling-firms-license-fees-kenya',
    title: 'Land Buying & Selling Firms in Kenya Face KES 500M License Fees: Impact on the Market',
    excerpt: 'Analyzing the new regulatory changes requiring land firms to pay significant license fees and their potential effects on land prices and market operations in Kenya for 2025.',
    author: 'Peter Kinyanjui',
    category: 'Policy',
    date: '2025-09-10',
    readTime: '9 min read',
    image: 'https://www.buyrentkenya.com/discover/wp-content/uploads/2023/07/brkmarketing-image-of-kenyan-members-of-parliament-giving-a-pre-7ba7835a-1c89-4182-bfc5-99860b06c78a-1.png',
    featured: false,
  },
  {
    id: 'mombasa-gate-bridge-project-real-estate-impact',
    title: 'Mombasa Gate Bridge Project: Changing the Landscape of Coastal Real Estate',
    excerpt: 'A comprehensive review of the Mombasa Gate Bridge project and its projected transformative impact on infrastructure, accessibility, and real estate values in Kenya\'s coastal region.',
    author: 'Fatuma Hassan',
    category: 'Infrastructure',
    date: '2025-09-15',
    readTime: '11 min read',
    image: 'https://swalanyeti.co.ke/storage/uploads/2024/01/Mombasa%20Gate%20bridge%201-1706616576.jpeg',
    featured: true,
  },
  {
    id: 'jkia-westlands-expressway-traffic-menace',
    title: 'JKIA-Westlands Expressway: Has It Solved Nairobi\'s Traffic Menace in 2025?',
    excerpt: 'An evaluation of the effectiveness of the JKIA-Westlands Expressway in alleviating Nairobi\'s notorious traffic congestion and its broader impact on urban mobility and real estate access in 2025.',
    author: 'Joseph Maina',
    category: 'Infrastructure',
    date: '2025-09-20',
    readTime: '10 min read',
    image: 'https://samrack.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-20-at-6.56.13-PM.png',
    featured: false,
  },
  {
    id: 'kenya-affordable-housing-progress-challenges',
    title: "Kenya's Affordable Housing: Progress and Challenges",
    excerpt: "Delve into the current state of affordable housing initiatives in Kenya, highlighting key milestones achieved, persistent challenges, and potential solutions to bridge the housing gap.",
    author: 'David Omondi',
    category: 'Development',
    date: '2025-08-01',
    readTime: '10 min read',
    image: 'https://nairobileo.co.ke/storage/uploads/2024/12/Ruto%20Mukuru%20houses-1734768895.jpeg',
    featured: false,
  },
  {
    id: 'cs-wahome-housing-levy-funds-construction-home-ownership-lags',
    title: 'CS Wahome: Housing Levy Funds Construction, But Home Ownership Lags',
    excerpt: 'An exploration of the Housing Levy\'s impact on construction funding versus the actual rate of homeownership, scrutinizing the disparities and policy implications as stated by CS Wahome.',
    author: 'Aisha Khan',
    category: 'Government Policy',
    date: '2025-07-22',
    readTime: '11 min read',
    image: 'https://publish.eastleighvoice.co.ke/mugera_lock/uploads/2025/02/Alice-Wahome-2.jpg',
    featured: false,
  },
  {
    id: 'did-kenya-state-house-need-makeover',
    title: "Did Kenya's State House Need a Makeover?",
    excerpt: 'A nuanced look at the recent renovations and expenditures on Kenya\'s State House, discussing the public perception, historical context, and economic implications in the current climate.',
    author: 'Kiplagat Ruto',
    category: 'Current Affairs',
    date: '2025-06-10',
    readTime: '9 min read',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcEMywzPoElIrDvs91zNfdH7kXEN-DeI7g7w&s',
    featured: false,
  },
  {
    id: 'environmental-oversight-halts-langata-housing-project',
    title: "Environmental Oversight Halts Lang'ata Housing Project",
    excerpt: 'Examining the reasons behind the suspension of a major housing project in Lang\'ata due to environmental concerns, underscoring the growing importance of sustainability in real estate development.',
    author: 'Sophia Nzomo',
    category: 'Sustainability',
    date: '2025-08-15',
    readTime: '10 min read',
    image: 'https://nairobiwire.com/wp-content/uploads/2025/05/afford.jpg',
    featured: false,
  },
  {
    id: 'kra-new-system-tax-filing-landlords-agents',
    title: 'KRA Launches New System to Make Tax Filing Easier for Landlords and Agents',
    excerpt: 'A detailed breakdown of the Kenya Revenue Authority\'s (KRA) new digital system designed to simplify tax compliance for real estate landlords and agents, and its potential impact.',
    author: 'James Mwangi',
    category: 'Taxation',
    date: '2025-09-01',
    readTime: '8 min read',
    image: 'https://www.mwakilishi.com/sites/default/files/styles/large/public/2023-01/Fc85dDst%20%282%29.jpg?itok=vPFzgRJR',
    featured: false,
  },
  {
    id: 'kuscco-scandal-ksh-12b-fraud-sacco-housing-risk',
    title: 'KUSCCO Scandal: KSh 12B Fraud Puts SACCO Housing at Risk',
    excerpt: 'Investigating the ramifications of the KSh 12 billion fraud scandal involving KUSCCO, and how this affects the stability and future of SACCO-backed housing projects in Kenya.',
    author: 'Njeri Kamau',
    category: 'Finance',
    date: '2025-07-05',
    readTime: '13 min read',
    image: 'https://media.licdn.com/dms/image/v2/D4D12AQEUdvYcXQfFSw/article-cover_image-shrink_720_1280/B4DZVbIqR2HAAI-/0/1740990752474?e=2147483647&v=beta&t=5h0xJQN4JdI-8XaH8sABeT2H8KDv7ZF-nFD5nYmQB34',
    featured: true,
  },
  {
    id: 'win-real-estate-investors-against-off-plan-developer',
    title: 'Win for Real Estate Investors Against Off-Plan Developer',
    excerpt: 'A case study detailing a landmark legal victory for real estate investors against a defaulting off-plan developer, offering crucial lessons for mitigating risks in off-plan purchases.',
    author: 'Daniel Otieno',
    category: 'Legal',
    date: '2025-08-20',
    readTime: '11 min read',
    image: 'https://www.wynnconsult.co.ke/wp-content/uploads/2023/09/1680684458222.png',
    featured: false,
  },
  {
    id: 'bpo-boom-commercial-developers-rethink-office-spaces',
    title: 'BPO Boom: Why Commercial Developers Must Rethink Office Spaces',
    excerpt: 'Exploring how the flourishing Business Process Outsourcing (BPO) sector in Kenya is reshaping demand for commercial office spaces, urging developers to innovate in design and functionality.',
    author: 'Catherine Chege',
    category: 'Commercial Real Estate',
    date: '2025-09-10',
    readTime: '9 min read',
    image: 'https://trendipgroup.co.za/wp-content/uploads/2024/07/Commercial_Office_Cape_Town_Design_and_Build_1st_floor_boardroom-4.jpg',
    featured: false,
  },
  {
    id: 'why-commercial-real-estate-kenya-facing-new-challenges',
    title: 'Why Commercial Real Estate in Kenya is Facing New Challenges',
    excerpt: 'An analysis of the evolving landscape of commercial real estate in Kenya, addressing new challenges such as remote work trends, oversupply, and shifting economic conditions.',
    author: 'Peter Kihara',
    category: 'Market Trends',
    date: '2025-07-28',
    readTime: '10 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-commercial-property',
    featured: false,
  },
  {
    id: 'northlands-heights-apartments-look-inside',
    title: 'Northlands Heights Apartments – A Look Inside',
    excerpt: 'A comprehensive review and virtual tour of the highly anticipated Northlands Heights Apartments, offering insights into their design, amenities, and investment potential.',
    author: 'Esther Wambui',
    category: 'Property Review',
    date: '2025-06-25',
    readTime: '8 min read',
    image: 'https://source.unsplash.com/random/800x600?northlands-apartments',
    featured: false,
  },
  {
    id: 'rise-branded-residences-kenya',
    title: 'The Rise of Branded Residences in Kenya',
    excerpt: 'Unpacking the growing trend of branded residences in Kenya, where luxury hospitality brands are partnering with developers to offer exclusive living experiences.',
    author: 'Samuel Kariuki',
    category: 'Luxury Real Estate',
    date: '2025-09-05',
    readTime: '10 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-branded-residences',
    featured: true,
  },
  {
    id: 'how-urbanisation-redefining-housing-kenya',
    title: 'How Urbanisation is Redefining Housing in Kenya',
    excerpt: 'An examination of how rapid urbanization is profoundly impacting housing patterns and demand in Kenya, leading to innovative solutions and concentrated development in urban centers.',
    author: 'Joyce Akinyi',
    category: 'Urban Planning',
    date: '2025-08-25',
    readTime: '11 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-urban-housing',
    featured: false,
  },
  {
    id: '6-types-residential-buildings-kenya-perfect-fit',
    title: '6 Types of Residential Buildings in Kenya: Find the Perfect Fit',
    excerpt: 'A practical guide outlining the various types of residential properties available in Kenya, helping prospective homeowners and investors understand their options and make informed decisions.',
    author: 'Michael Okello',
    category: 'Home Buying Guide',
    date: '2025-07-10',
    readTime: '9 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-residential-types',
    featured: false,
  },
  {
    id: 'how-to-build-cost-effectively-without-compromising-quality',
    title: 'How to Build Cost-Effectively Without Compromising on Quality',
    excerpt: 'Practical strategies and tips for developers and individual builders in Kenya to reduce construction costs while maintaining high standards of quality and durability.',
    author: 'Collins Kipkemoi',
    category: 'Construction',
    date: '2025-09-15',
    readTime: '12 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-cost-effective-building',
    featured: false,
  },
  {
    id: 'interest-rates-how-they-impact-your-mortgage',
    title: 'Interest Rates and How They Impact Your Mortgage',
    excerpt: 'A comprehensive guide explaining the intricacies of interest rates in Kenya and their direct influence on mortgage payments, affordability, and the overall real estate market.',
    author: 'Monica Wanjiru',
    category: 'Mortgage & Finance',
    date: '2025-08-08',
    readTime: '10 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-mortgage-rates',
    featured: false,
  },
  {
    id: 'why-homeownership-rates-dropping-urban-areas',
    title: 'Why Are Homeownership Rates Dropping in Urban Areas?',
    excerpt: 'Investigating the factors contributing to the decline in homeownership rates within Kenya\'s urban centers, exploring economic shifts, affordability challenges, and changing lifestyle priorities.',
    author: 'Paul Kimani',
    category: 'Market Analysis',
    date: '2025-07-01',
    readTime: '11 min read',
    image: 'https://usafactsdata.blob.core.windows.net/flourish-screenshots/what_is_the_homeownership_rate-LOC__country-United_States-national_homeownership_rate_by_type_line_chart.png',
    featured: false,
  },
  {
    id: 'could-fractional-ownership-kenya-next-real-estate-trend',
    title: "Could Fractional Ownership Be Kenya's Next Real Estate Trend?",
    excerpt: "An insightful look into fractional ownership as an emerging investment model in Kenya's real estate sector, assessing its potential benefits, challenges, and market viability.",
    author: 'Ruth Adhiambo',
    category: 'Investment Trends',
    date: '2025-09-20',
    readTime: '10 min read',
    image: 'https://www.buyrentkenya.com/discover/wp-content/uploads/2025/04/image-fx-2025-04-01t144758527-1.jpg',
    featured: true,
  },
  {
    id: 'do-i-really-need-real-estate-agent-buying-house',
    title: 'Do I Really Need a Real Estate Agent When Buying a House?',
    excerpt: 'A balanced discussion on the role of real estate agents in Kenya, weighing the pros and cons of engaging an agent versus navigating the property market independently.',
    author: 'Benard Kiprotich',
    category: 'Buying Guide',
    date: '2025-06-18',
    readTime: '9 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-real-estate-agent',
    featured: false,
  },
  {
    id: 'best-grass-types-transform-lawn-create-dream-garden',
    title: 'Best Grass Types to Transform Your Lawn and Create a Dream Garden',
    excerpt: 'A practical guide for Kenyan homeowners on selecting the ideal grass types for their lawns, considering climate, maintenance, and aesthetic appeal to achieve a stunning garden.',
    author: 'Lillian Owino',
    category: 'Home Improvement',
    date: '2025-08-12',
    readTime: '8 min read',
    image: 'https://source.unsplash.com/random/800x600?kenya-garden-grass',
    featured: false,
  },
  {
    id: 'women-in-real-estate-breaking-barriers-kenya-property-industry',
    title: "Women in Real Estate: Breaking Barriers in Kenya's Property Industry",
    excerpt: "Celebrating the achievements and contributions of women in Kenya's real estate sector, highlighting their growing influence, leadership roles, and the challenges they overcome.",
    author: 'Christine Wanjiku',
    category: 'Industry Leaders',
    date: '2025-10-01',
    readTime: '11 min read',
    image: 'https://source.unsplash.com/random/800x600?women-kenya-real-estate',
    featured: true,
  },
  {
    id: 'ceo-elizabeth-lizzie-costabir-featured-ntv-women-in-business',
    title: "CEO Elizabeth 'Lizzie' Costabir Featured on NTV's 'Women in Business'",
    excerpt: 'A spotlight on Elizabeth Costabir\'s inspiring journey and insights shared during her feature on NTV\'s \'Women in Business,\' discussing her leadership and impact in the real estate industry.',
    author: 'Editor',
    category: 'Industry Leaders',
    date: '2025-10-05',
    readTime: '8 min read',
    image: 'https://source.unsplash.com/random/800x600?elizabeth-costabir-business',
    featured: false,
  },
  {
    id: 'celebrating-decade-excellence-elizabeth-costabir-real-estate-journey',
    title: "Celebrating a Decade of Excellence: Elizabeth Costabir's Real Estate Journey",
    excerpt: 'A retrospective look at Elizabeth Costabir\'s ten-year career in real estate, chronicling her milestones, contributions, and vision for the future of the Kenyan property market.',
    author: 'Editorial Team',
    category: 'Industry Leaders',
    date: '2025-10-10',
    readTime: '10 min read',
    image: 'https://source.unsplash.com/random/800x600?elizabeth-costabir-celebration',
    featured: false,
  },
  {
    id: 'timeless-beauty-nairobi-colonial-era-buildings',
    title: "The Timeless Beauty of Nairobi's Colonial-Era Buildings",
    excerpt: "A captivating journey through Nairobi's architectural heritage, admiring the enduring charm and historical significance of its colonial-era buildings and their place in modern urban planning.",
    author: 'Historian',
    category: 'Architecture',
    date: '2025-06-30',
    readTime: '11 min read',
    image: 'https://source.unsplash.com/random/800x600?nairobi-colonial-architecture',
    featured: false,
  },
  {
    id: 'home-buying-tips',
    title: 'Essential Home Buying Tips for First-Time Buyers',
    excerpt:
      'Navigate the home buying process with confidence using these expert tips and strategies for first-time buyers.',
    content:
      'Buying your first home is an exciting milestone, but it can also feel overwhelming...',
    author: 'Mark Muriithi',
    category: 'Tips',
    date: '2025-02-05',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: true,
  },
  {
    id: 'serviced-apartments-vs-hotels',
    title: 'Services apartments vs Hotels: Which is Right for You?',
    excerpt:
      'Investing in serviced apartments is a fairly new concept, especially in the Kenyan real estate market.',
    content:
      'Sustainability has become a driving force in modern home design and construction...',
    author: 'Mark Muriithi',
    category: 'Trends',
    date: '2024-05-13',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/923357109.jpeg',
  },
  {
    id: 'real-estate-investment-amount-kenya',
    title: 'How Much Do You Need to Invest in Real Estate in Kenya',
    excerpt:
      'Investing in real estate in Kenya has become a popular option for many investors looking to diversify their portfolios and build long-term wealth.',
    content:
      'Investing in real estate in Kenya has become a popular option for many investors looking...',
    author: 'Mark Muriithi',
    category: 'Investment',
    date: '2023-07-19',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
  },
  {
    id: 'making-money-real-estate-kenya',
    title: 'How to Make Money in Real Estate in Kenya',
    excerpt:
      'Overview of the real estate in Kenya. Real estate in Kenya is one of the most lucrative investment opportunities available today.',
    content:
      'The mortgage landscape continues to evolve, and staying informed is crucial for buyers...',
    author: 'Mark Muriithi',
    category: 'Updates',
    date: '2022-10-10',
    readTime: '15 min read',
    image: 'https://images.ctfassets.net/eoa1vvg9v30r/1dFqN08SsUlz9PLb8CfU8g/8792a8bb4464c768a8e93570819fe362/How_to_invest_in_real_estate_Kenya_to_make_money.png',
  },
  {
    id: 'what-is-real-estate-investment',
    title: 'What is Real Estate Investment?',
    excerpt:
      'Real estate investment involves purchasing, owning, managing, renting, or selling real estate for profit.',
    content:
      'Real estate investment is a strategy that involves investing money in property with the expectation...',
    author: 'Mark Muriithi',
    category: 'Investment',
    date: '2023-07-19',
    readTime: '7 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
  },
  {
    id: 'boost-home-value',
    title: '10 Ways to Boost Your Home Value Before Selling',
    excerpt:
      'Maximize your property\'s market appeal and value with these strategic home improvement tips.',
    content:
      'Selling your home is a significant financial decision, and maximizing its value is crucial...',
    author: 'Mark Muriithi',
    category: 'Tips',
    date: '2024-03-10',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
  },
  {
    id: 'kenya-real-estate-2025-outlook',
    title: 'Kenya Real Estate Outlook 2025: Navigating Growth and Challenges',
    excerpt: 'A comprehensive analysis of Kenya\'s real estate market projections for 2025, examining growth opportunities, potential challenges, and strategic insights for investors and homebuyers.',
    author: 'Murivest Research Team',
    category: 'Market Analysis',
    date: '2025-01-15',
    readTime: '15 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: true,
  },
  {
    id: 'political-impact-property-kenya',
    title: 'How Political Stability Shapes the Real Estate Landscape in Kenya',
    excerpt: 'Exploring the intricate relationship between political dynamics and property market trends in Kenya, and how policy changes and stability influence investment decisions.',
    author: 'Dr. Samuel Ochieng',
    category: 'Market Trends',
    date: '2025-02-01',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'affordable-housing-initiatives-kenya',
    title: 'Kenya\'s Affordable Housing Agenda: Opportunities for Developers and Homeowners',
    excerpt: 'An in-depth look at Kenya\'s affordable housing initiatives and how they are creating new opportunities for property developers and potential homeowners across the country.',
    author: 'Hassan Ibrahim',
    category: 'Development',
    date: '2025-02-10',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'land-investment-satellite-towns',
    title: 'Unlocking Value: Land Investment in Kenya\'s Satellite Towns',
    excerpt: 'A strategic guide to land investment opportunities in Kenya\'s rapidly developing satellite towns, highlighting key areas with high growth potential.',
    author: 'James Njoroge',
    category: 'Investment',
    date: '2025-02-15',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'economic-indicators-property-market',
    title: 'Key Economic Indicators to Watch for Real Estate Investors in Kenya',
    excerpt: 'Understanding how GDP growth, inflation rates, and employment figures impact Kenya\'s property market and guide investment decisions.',
    author: 'Dr. Sarah Aketch',
    category: 'Market Analysis',
    date: '2025-02-20',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'commercial-real-estate-nairobi-trends',
    title: 'The Evolution of Commercial Real Estate in Nairobi: Post-Pandemic Shifts',
    excerpt: 'Analyzing how commercial real estate in Nairobi has transformed since the pandemic, including changes in demand, tenant preferences, and emerging opportunities.',
    author: 'Michael Chang',
    category: 'Commercial Real Estate',
    date: '2025-02-25',
    readTime: '14 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: true,
  },
  {
    id: 'green-building-kenya-sustainability',
    title: 'Building Green: The Rise of Sustainable Real Estate in Kenya',
    excerpt: 'Exploring the growing trend of green building practices in Kenya\'s real estate sector and the benefits of sustainable development for investors and the environment.',
    author: 'Eng. Patricia Odhiambo',
    category: 'Sustainability',
    date: '2025-03-01',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'diaspora-investment-kenya-property',
    title: 'Diaspora Investment: Tapping into Kenya\'s Booming Property Market from Abroad',
    excerpt: 'A comprehensive guide for Kenyans in the diaspora looking to invest in property back home, covering legal requirements, financing options, and best practices.',
    author: 'Grace Wahu',
    category: 'Diaspora Investment',
    date: '2025-03-05',
    readTime: '15 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: true,
  },
  {
    id: 'nairobi-expressway-real-estate-impact',
    title: 'The Nairobi Expressway: Reshaping Real Estate Values Along Its Corridor',
    excerpt: 'Examining how the Nairobi Expressway has influenced property values, development patterns, and investment opportunities along its route.',
    author: 'John Mwaura',
    category: 'Infrastructure',
    date: '2025-03-10',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'property-management-tips-kenya',
    title: 'Essential Property Management Tips for Landlords in Kenya',
    excerpt: 'Best practices for managing rental properties in Kenya, from tenant screening to maintenance and legal compliance.',
    author: 'Samuel Kamau',
    category: 'Property Management',
    date: '2025-03-15',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'short-term-rentals-investment-kenya',
    title: 'Short-Term Rentals: Unlocking High Yields in Kenya\'s Tourism & Business Hubs',
    excerpt: 'Analyzing the potential of short-term rental investments in Kenya\'s key tourism destinations and business centers.',
    author: 'Lisa Njeri',
    category: 'Investment',
    date: '2025-03-20',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'impact-inflation-property-kenya',
    title: 'The Impact of Inflation on Real Estate Investments in Kenya',
    excerpt: 'Understanding how inflation affects property values, rental incomes, and investment returns in Kenya\'s real estate market.',
    author: 'Dr. Emmanuel Ooko',
    category: 'Market Analysis',
    date: '2025-03-25',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'understanding-property-tax-kenya',
    title: 'Understanding Property Taxation in Kenya: A Comprehensive Guide',
    excerpt: 'A detailed guide to property taxes in Kenya, including rates, exemptions, and compliance requirements for property owners.',
    author: 'Tax Expert',
    category: 'Legal',
    date: '2025-03-30',
    readTime: '14 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'student-accommodation-investment',
    title: 'Student Accommodation in Kenya: A High-Yield Niche Investment',
    excerpt: 'Exploring investment opportunities in purpose-built student accommodation near universities in Kenya.',
    author: 'David Maina',
    category: 'Investment',
    date: '2025-04-01',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'land-reforms-impact-kenya',
    title: 'Land Reforms in Kenya: Navigating the Changing Landscape of Ownership',
    excerpt: 'An overview of recent land policy reforms in Kenya and their implications for property owners and investors.',
    author: 'Legal Analyst',
    category: 'Policy',
    date: '2025-04-05',
    readTime: '13 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'urbanization-driving-property-demand',
    title: 'Urbanization: The Unstoppable Force Driving Kenya\'s Property Demand',
    excerpt: 'How Kenya\'s rapid urbanization is fueling demand for housing and commercial real estate across the country.',
    author: 'Urban Planner',
    category: 'Market Trends',
    date: '2025-04-10',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'real-estate-investment-trusts-kenya',
    title: 'Real Estate Investment Trusts (REITs) in Kenya: A Comprehensive Guide',
    excerpt: 'Understanding how REITs work in Kenya and their potential as an alternative investment vehicle for property investors.',
    author: 'Financial Analyst',
    category: 'Investment',
    date: '2025-04-15',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'how-to-buy-commercial-property',
    title: 'How to Buy Commercial Property: A Step-by-Step Guide for Kenyan Investors',
    excerpt: 'A comprehensive guide to purchasing commercial real estate in Kenya, from property search to closing the deal.',
    author: 'Commercial Real Estate Expert',
    category: 'Commercial Real Estate',
    date: '2025-04-20',
    readTime: '16 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: true,
  },
  {
    id: 'property-valuation-software-kenya',
    title: 'Modern Property Valuation: Software and Tools for Kenyan Investors',
    excerpt: 'Exploring the latest valuation tools and software available for accurately assessing property values in Kenya.',
    author: 'Tech Analyst',
    category: 'Technology',
    date: '2025-04-25',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'property-development-cost-estimation',
    title: 'Property Development Cost Estimation in Kenya: What You Need to Know',
    excerpt: 'A practical guide to estimating development costs for property projects in Kenya, including land, construction, and soft costs.',
    author: 'Developer',
    category: 'Development',
    date: '2025-04-28',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'real-estate-technology-trends-kenya',
    title: 'PropTech Revolution: How Technology is Transforming Kenya\'s Real Estate Sector',
    excerpt: 'Exploring the impact of property technology (PropTech) on buying, selling, and managing real estate in Kenya.',
    author: 'Tech Journalist',
    category: 'Technology',
    date: '2025-05-01',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'apartment-investment-westlands-nairobi',
    title: 'Apartment Investment in Westlands, Nairobi: Opportunities and Considerations',
    excerpt: 'Analyzing the apartment investment landscape in Westlands, one of Nairobi\'s premium property markets.',
    author: 'Real Estate Analyst',
    category: 'Investment',
    date: '2025-05-05',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'property-security-systems-kenya',
    title: 'Modern Security Systems for Kenyan Properties: Protecting Your Investment',
    excerpt: 'A guide to implementing effective security systems for residential and commercial properties in Kenya.',
    author: 'Security Expert',
    category: 'Technology',
    date: '2025-05-08',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'auction-glossary',
    title: 'Property Auction Glossary: Key Terms Every Kenyan Investor Should Know',
    excerpt: 'Essential terminology for navigating property auctions in Kenya, from reserve prices to hammer prices.',
    author: 'Auction Expert',
    category: 'Auctions',
    date: '2025-05-10',
    readTime: '7 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'real-estate-negotiation-strategies',
    title: 'Mastering Real Estate Negotiation: Strategies for Kenyan Buyers and Sellers',
    excerpt: 'Proven negotiation techniques for getting the best deals in Kenya\'s property market.',
    author: 'Negotiation Coach',
    category: 'Tips',
    date: '2025-05-12',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'holiday-homes-coastal-kenya',
    title: 'Holiday Homes on Kenya\'s Coast: A Viable Investment Option?',
    excerpt: 'Evaluating the investment potential of holiday homes in Mombasa, Diani, and other coastal destinations.',
    author: 'Coastal Property Expert',
    category: 'Investment',
    date: '2025-05-15',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'kenya-mortgage-rates-outlook-2026',
    title: 'Kenya Mortgage Rates Outlook 2026: Trends and Predictions',
    excerpt: 'Expert analysis of mortgage rate trends and their implications for the Kenyan property market in 2026.',
    author: 'Banking Analyst',
    category: 'Mortgage & Finance',
    date: '2025-05-20',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'nairobi-office-space-outlook-2026',
    title: 'Nairobi Office Space Outlook 2026: Trends and Opportunities',
    excerpt: 'Comprehensive analysis of Nairobi\'s commercial office space market, including trends, vacancies, and investment opportunities.',
    author: 'Commercial Real Estate Analyst',
    category: 'Commercial Real Estate',
    date: '2025-05-25',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: true,
  },
  {
    id: 'land-valuation-myths-kenya',
    title: 'Land Valuation Myths in Kenya: Separating Fact from Fiction',
    excerpt: 'Debunking common misconceptions about land valuation in Kenya and what buyers should really know.',
    author: 'Valuation Expert',
    category: 'Tips',
    date: '2025-05-28',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'konza-technopolis-status-report-2026',
    title: 'Konza Technopolis Status Report 2026: Real Estate Implications',
    excerpt: 'An update on the Konza Technopolis development and its potential impact on surrounding property values.',
    author: 'Urban Analyst',
    category: 'Development',
    date: '2025-06-01',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'diani-watamu-coastal-boom-2026',
    title: 'Coastal Real Estate Boom: Diani and Watamu Lead the Way in 2026',
    excerpt: 'Exploring the rapid growth of coastal real estate markets in Diani and Watamu.',
    author: 'Coastal Property Expert',
    category: 'Market Trends',
    date: '2025-06-05',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'kenya-property-tax-guide-2026',
    title: 'Kenya Property Tax Guide 2026: Updates and Compliance',
    excerpt: 'Latest updates on property taxation in Kenya and essential compliance tips for property owners.',
    author: 'Tax Consultant',
    category: 'Legal',
    date: '2025-06-08',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'ardhisasa-property-transfer-guide-2026',
    title: 'Ardhisasa: A Step-by-Step Guide to Digital Property Transfer in Kenya',
    excerpt: 'Navigating Kenya\'s digital land transaction system, Ardhisasa, for seamless property transfers.',
    author: 'Land Registrar',
    category: 'Technology',
    date: '2025-06-10',
    readTime: '14 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: true,
  },
  {
    id: 'cost-to-build-3-bedroom-house-kenya-2026',
    title: 'Cost to Build a 3-Bedroom House in Kenya: 2026 Estimates',
    excerpt: 'Detailed cost breakdown for constructing a 3-bedroom house in different locations across Kenya.',
    author: 'Construction Cost Expert',
    category: 'Development',
    date: '2025-06-12',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'sectional-properties-act-2026-impact',
    title: 'Sectional Properties Act 2026: What Property Buyers Need to Know',
    excerpt: 'Understanding the implications of the Sectional Properties Act for apartment buyers in Kenya.',
    author: 'Legal Expert',
    category: 'Legal',
    date: '2025-06-15',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'real-estate-crowdfunding-kenya-2026',
    title: 'Real Estate Crowdfunding in Kenya: Opportunities and Risks',
    excerpt: 'Exploring the emerging trend of real estate crowdfunding platforms in Kenya.',
    author: 'Fintech Analyst',
    category: 'Investment',
    date: '2025-06-18',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'nakuru-kisumu-investment-outlook-2026',
    title: 'Investment Outlook for Nakuru and Kisumu: Kenya\'s Growing Secondary Cities',
    excerpt: 'Analyzing real estate investment opportunities in Kenya\'s major secondary cities.',
    author: 'Regional Analyst',
    category: 'Market Analysis',
    date: '2025-06-20',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'off-grid-real-estate-kenya-2026',
    title: 'Off-Grid Living: Solar and Borehole Solutions for Kenyan Properties',
    excerpt: 'How off-grid solutions are influencing property development and values in Kenya.',
    author: 'Sustainability Expert',
    category: 'Technology',
    date: '2025-06-22',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'land-surveying-drone-tech-kenya',
    title: 'Modern Land Surveying: Drone Technology in Kenyan Real Estate',
    excerpt: 'How drone technology is revolutionizing land surveying in Kenya.',
    author: 'Surveying Expert',
    category: 'Technology',
    date: '2025-06-25',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'student-housing-investment-kenya-2026',
    title: 'Student Housing Investment: The Acorn Effect in Kenya',
    excerpt: 'How the Acorn model is transforming student housing investments in Kenya.',
    author: 'Investment Analyst',
    category: 'Investment',
    date: '2025-06-28',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'retirement-homes-investment-kenya-2026',
    title: 'Retirement Homes: An Emerging Investment Niche in Kenya',
    excerpt: 'Exploring investment opportunities in retirement and senior living communities in Kenya.',
    author: 'Healthcare Real Estate Analyst',
    category: 'Investment',
    date: '2025-07-01',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'legal-framework-fractional-property-kenya',
    title: 'Fractional Property Ownership in Kenya: Legal Framework and Considerations',
    excerpt: 'Understanding the legal aspects of fractional property ownership in Kenya.',
    author: 'Legal Consultant',
    category: 'Legal',
    date: '2025-07-05',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'industrial-warehousing-demand-kenya-2026',
    title: 'Industrial Warehousing Demand in Kenya: 2026 Outlook',
    excerpt: 'Analyzing the growing demand for industrial and warehouse spaces in Kenya.',
    author: 'Industrial Real Estate Analyst',
    category: 'Commercial Real Estate',
    date: '2025-07-08',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'blockchain-land-titles-kenya-future',
    title: 'Blockchain for Land Titles in Kenya: Future Prospects',
    excerpt: 'Exploring the potential of blockchain technology for secure land titling in Kenya.',
    author: 'Blockchain Expert',
    category: 'Technology',
    date: '2025-07-10',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'airbnb-vs-longterm-rental-math-2026',
    title: 'Airbnb vs Long-Term Rentals: The Math for Kenyan Investors in 2026',
    excerpt: 'Comparing the financial returns of short-term vacation rentals versus traditional rentals.',
    author: 'Investment Analyst',
    category: 'Investment',
    date: '2025-07-12',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'nairobi-cbd-office-to-residential-conversion',
    title: 'The CBD Office-to-Residential Conversion Trend in Nairobi',
    excerpt: 'How converting commercial offices to residential use is reshaping Nairobi\'s CBD.',
    author: 'Urban Development Expert',
    category: 'Development',
    date: '2025-07-15',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'property-insurance-kenya-guide-2026',
    title: 'Property Insurance in Kenya: A Complete Guide for 2026',
    excerpt: 'Comprehensive guide to property insurance options and coverage in Kenya.',
    author: 'Insurance Expert',
    category: 'Risk Management',
    date: '2025-07-18',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'land-banking-satellite-towns-2026',
    title: 'Land Banking in Kenya\'s Satellite Towns: Strategy and Returns',
    excerpt: 'Investment strategy analysis for land banking in Kenya\'s growing satellite towns.',
    author: 'Investment Strategist',
    category: 'Investment',
    date: '2025-07-20',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'green-mortgages-sustainability-kenya-2026',
    title: 'Green Mortgages: Sustainability Incentives in Kenya\'s 2026 Market',
    excerpt: 'How green mortgage products are promoting sustainable real estate in Kenya.',
    author: 'Banking Analyst',
    category: 'Mortgage & Finance',
    date: '2025-07-22',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'ai-property-valuers-kenya-2026',
    title: 'AI-Powered Property Valuations: The Future in Kenya',
    excerpt: 'How artificial intelligence is transforming property valuation methods in Kenya.',
    author: 'PropTech Analyst',
    category: 'Technology',
    date: '2025-07-25',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'tigoni-real-estate-boom-2026',
    title: 'Tigoni Real Estate Boom: Nairobi\'s Suburban Growth Story',
    excerpt: 'Analyzing the rapid growth and investment potential of Tigoni\'s real estate market.',
    author: 'Regional Analyst',
    category: 'Market Trends',
    date: '2025-07-28',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'construction-vat-impact-kenya-2026',
    title: 'Construction VAT Changes: Impact on Kenyan Real Estate in 2026',
    excerpt: 'Analyzing how recent VAT changes affect construction costs and property prices.',
    author: 'Tax Analyst',
    category: 'Taxation',
    date: '2025-07-30',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'bamboo-construction-materials-kenya-2026',
    title: 'Bamboo as Construction Material: Sustainable Building in Kenya',
    excerpt: 'Exploring the use of bamboo in sustainable real estate development in Kenya.',
    author: 'Sustainable Architecture Expert',
    category: 'Sustainability',
    date: '2025-08-01',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'digital-asset-tax-real-estate-tokenization',
    title: 'Digital Asset Tax and Real Estate Tokenization in Kenya',
    excerpt: 'Understanding the tax implications of property tokenization and digital assets.',
    author: 'Tax Expert',
    category: 'Taxation',
    date: '2025-08-05',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'nakuru-real-estate-growth-2026',
    title: 'Nakuru\'s City Status Impact on Real Estate Growth',
    excerpt: 'How Nakuru\'s elevation to city status is affecting property markets.',
    author: 'Regional Analyst',
    category: 'Market Analysis',
    date: '2025-08-08',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'kenya-national-building-code-2026-summary',
    title: 'Kenya National Building Code 2026: Summary and Compliance',
    excerpt: 'Key updates from the revised Kenya National Building Code and compliance requirements.',
    author: 'Building Inspector',
    category: 'Legal',
    date: '2025-08-10',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'national-property-tax-kenya-2026',
    title: 'The 0.3% National Property Tax: What You Need to Know',
    excerpt: 'Understanding Kenya\'s national property tax and its implications for property owners.',
    author: 'Tax Consultant',
    category: 'Taxation',
    date: '2025-08-12',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'syokimau-commuter-rail-real-estate-impact',
    title: 'Syokimau Commuter Rail: Driving Real Estate Development',
    excerpt: 'How the Syokimau commuter rail line is spurring real estate growth in the area.',
    author: 'Infrastructure Analyst',
    category: 'Infrastructure',
    date: '2025-08-15',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: '3d-printed-houses-kenya-2026-update',
    title: '3D Printed Houses in Kenya: 2026 Update',
    excerpt: 'The latest developments in 3D printed housing technology in Kenya.',
    author: 'Construction Technology Expert',
    category: 'Technology',
    date: '2025-08-18',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'kilifi-real-estate-investment-guide-2026',
    title: 'Kilifi Real Estate Investment Guide 2026',
    excerpt: 'Comprehensive investment guide for Kilifi\'s growing real estate market.',
    author: 'Coastal Property Expert',
    category: 'Investment',
    date: '2025-08-20',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'crowdfunding-legal-due-diligence-kenya',
    title: 'Real Estate Crowdfunding: Legal Due Diligence for Kenyan Investors',
    excerpt: 'Essential legal checks before investing in property crowdfunding platforms.',
    author: 'Legal Expert',
    category: 'Legal',
    date: '2025-08-22',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'hempcrete-sustainable-building-materials-kenya',
    title: 'Hempcrete: Sustainable Building for Kenyan Real Estate',
    excerpt: 'Exploring hempcrete as an eco-friendly building material for Kenya.',
    author: 'Sustainable Building Expert',
    category: 'Sustainability',
    date: '2025-08-25',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'upper-hill-vs-westlands-office-market-2026',
    title: 'Upper Hill vs. Westlands: Nairobi\'s Premium Office Market Comparison',
    excerpt: 'Comparing investment potential of Upper Hill and Westlands office markets.',
    author: 'Commercial Real Estate Analyst',
    category: 'Commercial Real Estate',
    date: '2025-08-28',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'kenya-reit-market-growth-2026',
    title: 'The Return of REITs: Kenya\'s REIT Market Growth 2026',
    excerpt: 'Analyzing the resurgence of REIT investments in Kenya\'s property market.',
    author: 'Financial Analyst',
    category: 'Investment',
    date: '2025-08-30',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'expat-rental-market-nairobi-2026',
    title: 'The Expat Rental Market in Nairobi: Trends and Opportunities',
    excerpt: 'Analyzing the demand for rental properties from expatriates in Nairobi.',
    author: 'Rental Market Analyst',
    category: 'Rental Market',
    date: '2025-09-01',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'eldoret-residential-real-estate-2026',
    title: 'Eldoret\'s Champion Residential Boom: Investment Analysis',
    excerpt: 'Exploring the rapid growth of Eldoret\'s residential real estate market.',
    author: 'Regional Analyst',
    category: 'Market Analysis',
    date: '2025-09-05',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'land-fraud-prevention-kenya-2026',
    title: 'Avoiding Title Deed Scams in Kenya: 2026 Guide',
    excerpt: 'Essential tips for protecting yourself from land fraud in Kenya.',
    author: 'Legal Expert',
    category: 'Risk Management',
    date: '2025-09-08',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: true,
  },
  {
    id: 'kikuyu-satellite-town-investment-2026',
    title: 'Mixed-Use Pods: The Kikuyu Model for Satellite Town Development',
    excerpt: 'Analyzing the mixed-use development model in Kikuyu satellite town.',
    author: 'Urban Planner',
    category: 'Development',
    date: '2025-09-10',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'smart-irrigation-landscaping-kenya-2026',
    title: 'Smart Irrigation Systems for Kenyan Properties',
    excerpt: 'How smart irrigation is adding value to residential properties in Kenya.',
    author: 'Landscaping Expert',
    category: 'Technology',
    date: '2025-09-12',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'top-real-estate-agents-kenya-2026',
    title: 'Top Real Estate Agents in Kenya: 2026 Rankings',
    excerpt: 'Guide to finding and working with top real estate agents in Kenya.',
    author: 'Industry Reporter',
    category: 'Tips',
    date: '2025-09-15',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'nanyuki-eco-resort-boom-2026',
    title: 'Nanyuki\'s Eco-Resort Boom: Investment Opportunities',
    excerpt: 'Exploring investment potential in Nanyuki\'s growing eco-tourism real estate.',
    author: 'Tourism Property Expert',
    category: 'Investment',
    date: '2025-09-18',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'nairobi-railway-city-project-update-2026',
    title: 'Nairobi Railway City Project: 2026 Status Update',
    excerpt: 'Latest developments in the Nairobi Railway City smart city project.',
    author: 'Project Analyst',
    category: 'Development',
    date: '2025-09-20',
    readTime: '12 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'kenya-real-estate-market-predictions-2030',
    title: 'Kenya Real Estate 2030: Market Predictions and Investment Strategy',
    excerpt: 'Long-term projections for Kenya\'s real estate market through 2030.',
    author: 'Market Analyst',
    category: 'Market Analysis',
    date: '2025-09-22',
    readTime: '14 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: true,
  },
  {
    id: 'diani-digital-nomad-visa-impact',
    title: 'Digital Nomads in Diani: The New Real Estate Market',
    excerpt: 'How Kenya\'s digital nomad visa is affecting Diani\'s property market.',
    author: 'Expat Property Analyst',
    category: 'Market Trends',
    date: '2025-09-25',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'common-land-valuation-mistakes-kenya',
    title: 'Common Land Valuation Mistakes in Kenya: How to Avoid Them',
    excerpt: 'Pitfalls to avoid when valuing land in Kenya\'s property market.',
    author: 'Valuation Expert',
    category: 'Tips',
    date: '2025-09-28',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'tatu-city-living-standards-2026',
    title: 'Tatu City: Living Standards and Real Estate Values in 2026',
    excerpt: 'Analyzing living standards and property values in Tatu City.',
    author: 'New City Analyst',
    category: 'Development',
    date: '2025-09-30',
    readTime: '11 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'luxury-prefab-homes-naivasha-2026',
    title: 'Luxury Prefabricated Homes: The Naivasha Market in 2026',
    excerpt: 'Growth of luxury prefabricated homes in Naivasha\'s property market.',
    author: 'Construction Analyst',
    category: 'Development',
    date: '2025-10-02',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'small-commercial-retail-trends-kenya-2026',
    title: 'Small-Scale Commercial: The "Duka" Model for Kenyan Investors',
    excerpt: 'Investment potential in small-scale commercial retail properties in Kenya.',
    author: 'Retail Property Analyst',
    category: 'Commercial Real Estate',
    date: '2025-10-05',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'eldoret-student-housing-market-2026',
    title: 'Student Housing Market in Eldoret: Investment Outlook',
    excerpt: 'Growing opportunities in Eldoret\'s student housing market.',
    author: 'Education Property Analyst',
    category: 'Investment',
    date: '2025-10-08',
    readTime: '10 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'machakos-gated-community-growth-2026',
    title: 'Gated Community Growth in Machakos: Investment Analysis',
    excerpt: 'Analyzing the rise of gated communities in Machakos county.',
    author: 'Regional Analyst',
    category: 'Market Trends',
    date: '2025-10-10',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'real-estate-photography-tips-kenya-2026',
    title: 'Real Estate Photography: Tips for Kenyan Properties in 2026',
    excerpt: 'Professional photography tips for selling or renting Kenyan properties.',
    author: 'Real Estate Photographer',
    category: 'Tips',
    date: '2025-10-12',
    readTime: '8 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: false,
  },
  {
    id: 'digital-tenant-management-apps-kenya',
    title: 'Managing Tenants Digitally: Best Apps for Kenyan Landlords',
    excerpt: 'Top digital tools for efficient tenant management in Kenya.',
    author: 'PropTech Expert',
    category: 'Technology',
    date: '2025-10-15',
    readTime: '9 min read',
    image: 'https://ext.same-assets.com/616702439/4224781709.jpeg',
    featured: false,
  },
  {
    id: 'kenya-real-estate-market-summary-2026',
    title: 'Kenya Real Estate Market Summary 2026: The Final Word',
    author: 'Murivest Research Team',
    category: 'Market Analysis',
    date: '2025-10-20',
    readTime: '15 min read',
    image: 'https://ext.same-assets.com/2009473017/2828581621.jpeg',
    featured: true,
    excerpt: 'Comprehensive year-end review of Kenya\'s real estate market performance.',
  },
  {
    id: 'duplex-triplex-fourplex',
    title: 'Duplex vs. Triplex vs. Fourplex for Investors',
    excerpt: 'Compare financing, management requirements, and risk factors across 2-4 unit properties to choose the right investment for your goals.',
    author: 'LoopNet Team',
    category: 'Investing',
    date: 'October 15, 2025',
    readTime: '10 min read',
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200',
    featured: false,
  },
];

const Blog = () => {
  const categories = ['All', 'Thought Leadership', 'Institutional Insights', 'Market Intelligence', 'Legal & Structuring', 'Sustainability & ESG', 'Private Equity', 'Asset Allocation', 'Economic Analysis', 'Investment Tips', 'Commercial Trends'];

  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');

  // Dummy filter logic (ensure 'blog' data is available in your scope)
  const filteredPosts: Blog[] = blog.filter(post => {
    const matchesCategory = selectedCategory === 'All' || post.category === selectedCategory;
    const matchesSearch = post.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         post.excerpt.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <section className="relative bg-[#F8F7F4] text-[#2C2C2C] overflow-hidden">
      {/* Hairline top border */}
      <div className="absolute top-0 left-0 w-full h-px bg-[#E5E2DC]" />
      
      <div className="max-w-[1400px] mx-auto px-6 md:px-12 lg:px-16 py-20 md:py-32">
        {/* Section Header */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-16 md:mb-24"
        >
          <div>
            <div className="flex items-center gap-3 mb-6">
              <div className="w-8 h-[1px] bg-[#8B7355]" />
              <p className="text-[11px] tracking-[0.4em] uppercase text-[#8B7355] font-medium">
                Market Intelligence
              </p>
            </div>
            
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-serif leading-[1.1] text-[#2C2C2C]">
              Latest <span className="italic text-[#8B7355] font-light">Insights</span>
            </h2>
          </div>

          <a 
            href="/insights"
            className="group inline-flex items-center gap-3 text-[12px] tracking-[0.2em] uppercase text-[#2C2C2C] font-medium hover:text-[#8B7355] transition-colors duration-500"
          >
            <span>View All Articles</span>
            <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform duration-300" />
          </a>
        </motion.div>

        {/* Blog Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-6">
          {filteredPosts.map((post, index) => (
            <motion.article
              key={post.id}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ 
                duration: 0.6, 
                delay: index * 0.1,
                ease: [0.16, 1, 0.3, 1] 
              }}
              className="group"
            >
              <a href={`/blog/${post.id}`} className="block">
                {/* Image */}
                <div className="relative aspect-[4/3] overflow-hidden bg-[#E5E2DC] mb-6">
                  <Image
                    src={post.image}
                    alt={post.title}
                    fill
                    className="object-cover grayscale group-hover:grayscale-0 group-hover:scale-105 transition-all duration-700"
                    sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
                  />
                  {/* Category badge */}
                  <div className="absolute top-4 left-4">
                    <span className="px-3 py-1 bg-[#F8F7F4] text-[11px] tracking-[0.2em] uppercase text-[#8B7355] font-medium">
                      {post.category}
                    </span>
                  </div>
                </div>

                {/* Content */}
                <div className="flex items-center gap-2 mb-3">
                  <Calendar className="w-3 h-3 text-[#8B7355]" />
                  <span className="text-[11px] tracking-[0.15em] uppercase text-[#5A5A5A]">
                    {post.date}
                  </span>
                </div>

                <h3 className="text-xl md:text-2xl font-serif mb-3 text-[#2C2C2C] group-hover:text-[#8B7355] transition-colors duration-500 line-clamp-2">
                  {post.title}
                </h3>

                <p className="text-[14px] leading-[1.7] text-[#5A5A5A] font-light mb-4 line-clamp-3">
                  {post.excerpt}
                </p>

                <span className="inline-flex items-center gap-2 text-[11px] tracking-[0.2em] uppercase text-[#8B7355] font-medium group-hover:text-[#2C2C2C] transition-colors duration-500">
                  <span>Read Analysis</span>
                  <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform duration-300" />
                </span>
              </a>
            </motion.article>
          ))}
        </div>
      </div>

      {/* Hairline bottom border */}
      <div className="absolute bottom-0 left-0 w-full h-px bg-[#E5E2DC]" />
    </section>
  );
};

export default Blog;